spring.application.name=api-gateway


server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Gateway Route to service-a
spring.cloud.gateway.routes[0].id=service-a
spring.cloud.gateway.routes[0].uri=lb://SERVICE-A
spring.cloud.gateway.routes[0].predicates[0]=Path=/a/**

# Gateway Route to auth-service
spring.cloud.gateway.routes[1].id=auth-service
spring.cloud.gateway.routes[1].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/auth/**

# Gateway Route to service-b
spring.cloud.gateway.routes[0].id=service-a
spring.cloud.gateway.routes[0].uri=lb://SERVICE-A
spring.cloud.gateway.routes[0].predicates[0]=Path=/a/**
