spring.application.name=auth-service
server.port=8082

# Eureka
eureka.client.service-url.defaultZone=http://13.62.98.131:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# IMPORTANT: Health check
eureka.client.healthcheck.enabled=true

# Actuator (REQUIRED for health check)
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Optional but recommended
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}